### ISSUE TITLE
Make groovy dependency explicit or "provided"

### ISSUE THREAD

**Issue by perbergland** [ReactiveX/RxGroovy#2]
The current dependency
    compile 'org.codehaus.groovy:groovy-all:2.+'
causes us troubles in our gradle builds as it brings in arbitrary versions of groovy (currently 2.4.0-beta3).
Since gradle doesn't support maven dependency exclusions, it's hard for us to build a library with rxgroovy and get the dependencies to work out - we would have to specify a forced groovy version in each leaf project to get it to work.

Suggestions:
Specify an explicit groovy version that you have compiled and tested against.
You could also make the dependency "provided" to have it not appear in the published pom file as per various solutions described in https://issues.gradle.org/browse/GRADLE-784

**Comment by ZacSweers** [comment]
Could you not do something like this?

``` groovy
compile 'org.codehaus.groovy:groovy-all:2.+' {
    exclude group: 'org.codehaus.groovy'
}
```

**Comment by perbergland** [comment]
It used to be that excluded transitive dependencies in gradle weren't kept in dependencies down the road, but it could be that has been fixed in recent gradle versions to actually include exclusions in the generated pom file for maven publishing.

**Comment by perbergland** [comment]
Too old - closing it now
